%{?!ros_distro:%global ros_distro rolling}
%global pkg_name rqt_gui
%global normalized_pkg_name %{lua:return (string.gsub(rpm.expand('%{pkg_name}'), '_', '-'))}

Name:           ros-rolling-rqt-gui
Version:        1.10.4
Release:        1%{?dist}
Summary:        ROS %{pkg_name} package

License:        BSD
URL:            http://ros.org/wiki/rqt_gui
Source0:        %{name}-%{version}.tar.gz

BuildRequires:  bloom-rpm-macros
BuildRequires:  python%{python3_pkgversion}-devel

%{?bloom_package}

%description
rqt_gui provides the main to start an instance of the ROS integrated graphical
user interface provided by qt_gui.


%package devel
Release:        %{release}%{?release_suffix}
Summary:        %{summary}
Provides:       %{name} = %{version}-%{release}
Provides:       %{name}%{?_isa} = %{version}-%{release}
Requires:       %{name}-runtime%{?_isa} = %{version}-%{release}

%description devel
rqt_gui provides the main to start an instance of the ROS integrated graphical
user interface provided by qt_gui.


%package runtime
Release:        %{release}
Summary:        %{summary}

%description runtime
rqt_gui provides the main to start an instance of the ROS integrated graphical
user interface provided by qt_gui.


%prep
%autosetup -p1


%generate_buildrequires
%bloom_buildrequires


%build
%py3_build


%install
%py3_install -- --prefix "%{bloom_prefix}"


%if 0%{?with_tests}
%check
# Look for a directory with a name indicating that it contains tests
TEST_TARGET=$(ls -d * | grep -m1 "^\(test\|tests\)" ||:)
if [ -n "$TEST_TARGET" ] && %__python3 -m pytest --version; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
%__python3 -m pytest $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif


%files devel
%dir %{bloom_prefix}
%ghost %{bloom_prefix}/share/%{pkg_name}/package.xml


%files runtime
%{bloom_prefix}


%changelog
* Fri Apr 24 2026 Dharini Dutia <dharini@openrobotics.org> - 1.10.4-1
- Autogenerated by Bloom

* Tue Apr 21 2026 Dharini Dutia <dharini@openrobotics.org> - 1.10.3-1
- Autogenerated by Bloom
